name: front-end github actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --prefix  Front-End/Image-Converter/
    - run: npm fund --prefix  Front-End/Image-Converter/
    - run: npm run build --if-present --prefix  Front-End/Image-Converter/
    - run: npm test --prefix  Front-End/Image-Converter/
