name: front-end github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci --prefix  Front-End/Image-Converter/
    - run: npm fund --prefix  Front-End/Image-Converter/
    - bash: |
      echo $(pwd)
    # - run: mv src/assets/glightbox.js node_modules/glightbox/src/js
    # - run: mv src/assets/glightbox.css node_modules/glightbox/src/postcss
    - run: npm run build --if-present --prefix  Front-End/Image-Converter/
    - run: npm test --prefix  Front-End/Image-Converter/
